# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emotion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'emotion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\remotion.proto\x12\x07\x65motion\"$\n\x0e\x45motionRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"j\n\tDetection\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05x_min\x18\x03 \x01(\x02\x12\r\n\x05y_min\x18\x04 \x01(\x02\x12\r\n\x05x_max\x18\x05 \x01(\x02\x12\r\n\x05y_max\x18\x06 \x01(\x02\"9\n\x0f\x45motionResponse\x12&\n\ndetections\x18\x01 \x03(\x0b\x32\x12.emotion.Detection2T\n\x0e\x45motionTracker\x12\x42\n\rDetectEmotion\x12\x17.emotion.EmotionRequest\x1a\x18.emotion.EmotionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMOTIONREQUEST']._serialized_start=26
  _globals['_EMOTIONREQUEST']._serialized_end=62
  _globals['_DETECTION']._serialized_start=64
  _globals['_DETECTION']._serialized_end=170
  _globals['_EMOTIONRESPONSE']._serialized_start=172
  _globals['_EMOTIONRESPONSE']._serialized_end=229
  _globals['_EMOTIONTRACKER']._serialized_start=231
  _globals['_EMOTIONTRACKER']._serialized_end=315
# @@protoc_insertion_point(module_scope)
