# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import emotion_pb2 as emotion__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in emotion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmotionTrackerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectEmotion = channel.unary_unary(
                '/emotion.EmotionTracker/DetectEmotion',
                request_serializer=emotion__pb2.EmotionRequest.SerializeToString,
                response_deserializer=emotion__pb2.EmotionResponse.FromString,
                _registered_method=True)


class EmotionTrackerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectEmotion(self, request, context):
        """O psicólogo envia um frame e recebe as detecções
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmotionTrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectEmotion': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectEmotion,
                    request_deserializer=emotion__pb2.EmotionRequest.FromString,
                    response_serializer=emotion__pb2.EmotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotion.EmotionTracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emotion.EmotionTracker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmotionTracker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectEmotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emotion.EmotionTracker/DetectEmotion',
            emotion__pb2.EmotionRequest.SerializeToString,
            emotion__pb2.EmotionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
